### ISSUE TITLE
Uncaught Error: Assertion Failed: tooltip has to exist on Ember.$.fn.tooltip

### ISSUE THREAD

**Issue by JimBarrows** [vsymguysung/ember-cli-summernote#2]
I get the following error with Ember-cli version 0.1.6,  straight install:
    Uncaught Error: Assertion Failed: tooltip has to exist on Ember.$.fn.tooltip     ember.js:3865
    Ember.assert     summer-note.js:33 
    Ember.Component.extend.didInsertElement     ember.js:19671 
    apply     ember.js:19245
    superWrapper     ember.js:40881
    EmberObject.extend.trigger     ember.js:19673
    apply     ember.js:19245 
    superWrapper     ember.js:39584 
    Renderer.didInsertElement     ember.js:10679 
    Renderer_renderTree     ember.js:10705 
    (anonymous function)     ember.js:679 
    DeferredActionQueues.invoke     ember.js:749 
    DeferredActionQueues.flush     ember.js:135 
    Backburner.end     ember.js:190 
    Backburner.run     ember.js:18223 
    run     ember.js:2542 
    runInitialize     jquery.js:3143 
    jQuery.Callbacks.fire     jquery.js:3255 
    jQuery.Callbacks.self.fireWith     jquery.js:3467 
    jQuery.extend.ready     jquery.js:3498 
    completed

**Comment by fiddler** [comment]
I was just playing with this and ran into same problem. The answer was in the documentation:
> The bootstrap and fontAwesome resources will not be imported to your resources by default.

I fixed it by installing Bootstrap to the project via bower and adding `app.import('bower_components/bootstrap/js/tooltip.js');` to my Brocfile.js, so jQuery has Bootstrap tooltip available. You'll probably want to also add CSS for Bootstrap and fontAwesome too, so that the editor looks good.

**Comment by vsymguysung** [comment]
Here is another solution in addition to @fiddler's great suggestion.
 You can just config ```the Brocfile.js``` file with the following configuration.
```
var app = new EmberAddon({
  'ember-cli-summernote': {
    "importBootstrapCSS": true,
    "importBootstrapJS": true,
    "importFontawesomeCSS": true
  }
});
```
Thanks.

**Comment by delkano** [comment]
Excuse me, I can't find the `Brocfile.js` where I am supposed to add this configuration; not even a `ember-cli-build.js` file which supposedly has replaced the Brocfiles.

**Comment by vsymguysung** [comment]
@delkano: As far as I remember,  my response above was written when the plugin was using a version below the `v1.13.1`.  Like you mentioned it, as long as you install a project with the ember-cli whose version is `v1.13.1` or higher, you will see the `ember-cli-build.js` file at the root level of the project.

**Comment by delkano** [comment]
You are right in that there is an `ember-cli-build.js` in root, and I have used it successfully to set the imports using @fiddler 's approach.
However, this code:
```
var app = new EmberAddon({
  'ember-cli-summernote': {
    "importBootstrapCSS": true,
    "importBootstrapJS": true,
    "importFontawesomeCSS": true
  }
});
```
would overwrite the app var in it, so I'm guessing it is not supposed to go there. However, I can't find a suitable place for it.
As I said, I already worked it out using `app.import`s, but it may be useful to update the readme to something actually clear and doable, since the component does otherwise work great with last versions.
